#!/usr/bin/env bash
# This script displays a list of currently running processes
# Shows all processes, for all users, including those which might not have a TT
# Shows process hierarchy

ps -a -x -u -f
