#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using the while loop + IFS (Internal Field Separator)

while IFS=' ' read -r f1 f2 f3 f4 f5 f6 f7; do
        echo "The user $f1 is part of the $f2 gang, lives in $f3 and rides $f4. $f5 place is protected by the passcode $f6, more info about the user here: $f7"
done < "/etc/passwd"
