#!/usr/bin/env bash
# This script is displaying loops from 1 to 10 and displays "bad luck for the 4th iteration, "good luck for the 8th iteration and "Best shool for the other iterations
var="Best School"
var2="bad luck"
var3="good luck"
i="0"
while [ $i -lt 10 ]; do
  if [ $i -eq 3 ]; then
          echo "$var2"
  elif [ $i -eq 7 ]; then
          echo "$var3"
  else
	  echo "$var"
  fi
  ((i++))
done
