#!/usr/bin/env bash
# This script cofigures an Ubuntu server; local host resolves to 127.0.0.2; facebook.com resolves to 8.8.8.8

#Back up of the original hosts file
cp /etc/hosts /etc/hosts.bak

  echo "127.0.0.2 localhost" > /etc/hosts
  echo "8.8.8.8 facebook.com" >> /etc/hosts
  echo "Hosts file updated successfully"
