#!/usr/bin/env bash
# This script cofigures an Ubuntu server; local host resolves to 127.0.0.2; facebook.com resolves to 8.8.8.8

  echo "127.0.0.2       localhost" > /etc/hosts
  echo "8.8.8.8         facebook.com" >> /etc/hosts
